Successfully set up pre-commit coding standards. A tutorial for how to set these up is in the README.

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,28 +1,15 @@
-#!/bin/sh
-# Pre-commit hook passing files through jslint
-#
-# This ensures that all js, html and json files are valid and conform
-# to expectations.
+#!/bin/bash
 
-ROOT_DIR=$(git rev-parse --show-toplevel)
-JSLINT="\"${ROOT_DIR}/node_modules/.bin/jslint\" "
-
-INDEXJS="\"C:\Users\David Shilliday\Desktop\Senior Design Repo\src\index.js\""
-	
-    if node $JSLINT $INDEXJS 2>&1 | grep 'No errors found' ; then
-        echo "jslint passed for index.js"
-        exit 0
-    else
-        node $JSLINT $INDEXJS
-        exit 1
-    fi  
-
-INDEXHTML="\"C:\Users\David Shilliday\Desktop\Senior Design Repo\src\index.html\""
-	
-    if node $JSLINT $INDEXHTML 2>&1 | grep 'No errors found' ; then
-        echo "jslint passed for index.js"
-        exit 0
-    else
-        node $JSLINT $INDEXHTML
-        exit 1
-    fi  
+# Ensure all JavaScript files staged for commit pass standard code style
+function xargs-r() {
+  # Portable version of "xargs -r". The -r flag is a GNU extension that
+  # prevents xargs from running if there are no input files.
+  if IFS= read -r -d $'\n' path; then
+    echo "$path" | cat - | xargs "$@"
+  fi
+}
+git diff --name-only --cached --relative | grep '\.jsx\?$' | sed 's/[^[:alnum:]]/\\&/g' | xargs-r -E '' -t standard
+if [[ $? -ne 0 ]]; then
+  echo 'JavaScript Standard Style errors were detected. Aborting commit.'
+  exit 1
+fi
